adopted: true
description: create a list from a playbook
id: 'a5b74d4d-5a48-4394-88b8-bb9717b9a643'
inputs: []
name: pcurrie_create_list
outlinetasks: {}
outputs: []
possibleresponses: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b8076caf-7d46-4082-862f-1b48349c7d9a
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: b8076caf-7d46-4082-862f-1b48349c7d9a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 2
    scriptarguments:
      listData:
        simple: 8.8.8.8,8.8.4.4
      listName:
        simple: pcurrie_test_listName
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.create
      id: 33701fd6-dad1-41c7-ab72-77b542613a04
      iscommand: true
      istaskmissingcomponenterrordismissed: false
      name: Create a list
      playbooktaskmissingcomponent: null
      script: Builtin|||createList
      type: regular
      version: -1
    taskid: 33701fd6-dad1-41c7-ab72-77b542613a04
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 220
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 2
    scriptarguments:
      listName:
        simple: pcurrie_test_listName
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.get
      id: 7aaff8f6-384e-4edc-8cff-41e67bc0dbc5
      iscommand: true
      istaskmissingcomponenterrordismissed: false
      name: Display a list
      playbooktaskmissingcomponent: null
      script: Builtin|||getList
      type: regular
      version: -1
    taskid: 7aaff8f6-384e-4edc-8cff-41e67bc0dbc5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      listData:
        simple: 1.2.3.4,5.6.7.8
      listName:
        simple: pcurrie_test_listName
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.add
      id: 0d5e1fe8-a93b-45a3-8874-d4b99ec4968e
      iscommand: true
      istaskmissingcomponenterrordismissed: false
      name: Add elements to list
      playbooktaskmissingcomponent: null
      script: Builtin|||addToList
      type: regular
      version: -1
    taskid: 0d5e1fe8-a93b-45a3-8874-d4b99ec4968e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 590
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 2
    scriptarguments:
      listName:
        simple: pcurrie_test_listName
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.get
      id: dc750d4f-ff80-4e14-888c-64676c1a2d21
      iscommand: true
      istaskmissingcomponenterrordismissed: false
      name: Display a list
      playbooktaskmissingcomponent: null
      script: Builtin|||getList
      type: regular
      version: -1
    taskid: dc750d4f-ff80-4e14-888c-64676c1a2d21
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 770
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      listData:
        simple: 1.2.3.4
      listName:
        simple: pcurrie_test_listName
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.remove
      id: ce9cad02-c392-4f3f-af3b-58db1ee7113a
      iscommand: true
      istaskmissingcomponenterrordismissed: false
      name: Remove elements to list
      playbooktaskmissingcomponent: null
      script: Builtin|||removeFromList
      type: regular
      version: -1
    taskid: ce9cad02-c392-4f3f-af3b-58db1ee7113a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 930
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      listName:
        simple: pcurrie_test_listName
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.get
      id: 779bcb82-f4d0-4789-850e-1dfbf60d3b47
      iscommand: true
      istaskmissingcomponenterrordismissed: false
      name: Display a list
      playbooktaskmissingcomponent: null
      script: Builtin|||getList
      type: regular
      version: -1
    taskid: 779bcb82-f4d0-4789-850e-1dfbf60d3b47
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1100
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1125,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
